services:
  db:
    image: postgres:15-alpine
    container_name: true_code_db
    restart: always
    env_file:
      - ./back/.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: true_code_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./back/.env
    depends_on:
      - db
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
      - ./back/uploads:/usr/src/app/uploads

  app:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: true_code_app
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  db:
